version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: filmkassen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d filmkassen"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/filmkassen
      DFI_API_BASE_URL: https://api.dfi.dk/v1
      DFI_API_USERNAME: hack4dk
      DFI_API_PASSWORD: qWSzXlO5I9Wdef_NKcOJ
      SECRET_KEY: your-secret-key-here-change-in-production
      CORS_ORIGINS: '["http://localhost:3000"]'
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:3000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
